name: "[Dispatch] apply workflows"

on:
  workflow_dispatch:
    inputs:
      dest:
        description: 'target repository({repository_name} or {topic1/topic2})'
        required: true
        default: 'identity'
      type:
        description: 'type of deployment (repository|topic)'
        required: true
        default: 'repository'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set git user
        run : |
          git config --global user.email admin@cloudforet.io
          git config --global user.signingkey "${{ secrets.CLOUDFORET_ADMIN_GPG_KEY_ID }}"
          git config --global user.name cloudforet-admin
      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6.2.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: set python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install requirements
        run: pip install -r requirements.txt
      - name: set PAT_TOKEN env
        run: echo "PAT_TOKEN=$(echo ${{ secrets.PAT_TOKEN }})" >> $GITHUB_ENV
      - name: apply workflows
        run: |
          python src/main.py --dest ${{ github.event.inputs.dest }} --type ${{ github.event.inputs.type }}
